<h1 class="text-center">Lista de Alunos</h1>
<div class="container col-8">

    <table class="table table-striped table-dark">
        <thead>
            <th>matricula</th>
            <th>nome</th>
            <th>cidade</th>
            <th>Ações</th>
        </thead>
        <?php
    foreach ($dados as $row) {
        $idalunos = $row['idalunos'];
        echo "<tr>
        <td>{$row['matricula']}</td>
        <td>{$row['nome']}</td>
        <td>{$row['cidade']}</td>
        <td>
        <a href='/editar?idalunos={$idalunos}' class='btn btn-warning'>Editar</a>
        <button type='button' class='btn btn-danger' data-bs-toggle='modal' data-bs-target='#exampleModal' onclick='enviarID({$idalunos})'>
  Delete
</button>
        </td>
        </tr>
        ";
    }
    ?>
    </table>
</div>
<!-- Modal -->
<div class='modal fade' id='exampleModal' tabindex='-1' aria-labelledby='exampleModalLabel' aria-hidden='true'>
    <div class='modal-dialog'>
        <div class='modal-content'>
            <div class='modal-header'>
                <h1 class='modal-title fs-5' id='exampleModalLabel'>APAGAR CADASTRO DE ALUNO</h1>
                <button type='button' class='btn-close' data-bs-dismiss='modal' aria-label='Close'></button>
            </div>
            <div class='modal-body'>
                DESEJA APAGAR ESSE ALUNO ?
                <input type="hidden" id="idatual">
            </div>
            <div class='modal-footer'>
                <button type='button' class='btn btn-secondary' data-bs-dismiss='modal'>Cancelar</button>
                <button type='button' onclick='confirmar()' class='btn btn-danger'>Confirmar</button>
            </div>
        </div>
    </div>
</div>

<script>
    function enviarID(id) {
        document.getElementById("idatual").value = id;
    }
    function confirmar() {
        let idalunos = document.getElementById("idatual").value;
        location.href = '/excluir?idalunos=' + idalunos;
    }
</script>
<!-- JavaScript Bundle with Popper -->
<script src='https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js'
    integrity='sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3'
    crossorigin='anonymous'></script>