<h1 class="text-center">Novo Aluno</h1>
<hr>
<div class="container col-4">
    <form class="form-control d-grid gap-2 col-3 mx-auto " action="#" method="post">
        <label for="matricula">Matricula</label>
        <input required value="<?php echo $_POST['$matricula'] ?? '' ?>" class="form-control col-3" type="text"
            name="matricula">
        <label for="nome">nome</label>
        <input required value="<?php echo $_POST['$nome'] ?? '' ?>" class="form-control" type="text" name="nome">
        <label for="cidade">cidade</label>
        <input required value="<?php echo $_POST['$cidade'] ?? '' ?>" class="form-control" type="text" name="cidade">
        <button class="btn btn-primary" type="submit" value="criar">Enviar</button>
    </form>
</div>