<h1>Novo Aluno</h1>
<hr>

<form class="form-control d-grid gap-2 col-3 mx-auto " action="#" method="post">
    <label for="matricula">Matricula</label>
    <input class="form-control col-3"type="text" name="matricula">
    <label for="nome">nome</label>
    <input class="form-control"type="text" name="nome">
    <label for="cidade">cidade</label>
    <input class="form-control"type="text" name="cidade">
    <button class="btn btn-primary" type="submit" value="criar">Enviar</button>
</form>